[platformio]
src_dir = examples/demo
default_envs=nanoatmega328

[env:nanoatmega328]
platform = atmelavr
framework = arduino
board = nanoatmega328
monitor_speed = 115200
build_flags = -Isrc -O0
build_type = debug

lib_deps = adafruit/Adafruit PWM Servo Driver Library@^3.0.3
	   adafruit/Adafruit BusIO@^1.16.2
	   Wire@^1.0.0
	   JLed=symlink://./../jled

